INSERT INTO `assist_course` 
VALUES
(1,1,NULL,NULL,NULL,NULL),
(2,1,NULL,NULL,NULL,NULL),
(3,1,NULL,NULL,NULL,NULL),
(4,1,NULL,NULL,NULL,NULL),
(5,1,NULL,NULL,NULL,NULL),
(6,1,NULL,NULL,NULL,NULL),
(7,1,NULL,NULL,NULL,NULL),
(8,1,NULL,NULL,NULL,NULL),
(9,1,NULL,NULL,NULL,NULL),
(10,1,NULL,NULL,NULL,NULL);
INSERT INTO `assist_course` 
VALUES
(1,2,NULL,NULL,NULL,NULL),
(2,2,NULL,NULL,NULL,NULL),
(3,2,NULL,NULL,NULL,NULL),
(4,2,NULL,NULL,NULL,NULL),
(5,2,NULL,NULL,NULL,NULL),
(6,2,NULL,NULL,NULL,NULL),
(7,2,NULL,NULL,NULL,NULL),
(8,2,NULL,NULL,NULL,NULL),
(14,2,NULL,NULL,NULL,NULL),
(15,2,NULL,NULL,NULL,NULL);
INSERT INTO `assist_course` 
VALUES
(1,3,NULL,NULL,NULL,NULL),
(2,3,NULL,NULL,NULL,NULL),
(3,3,NULL,NULL,NULL,NULL),
(4,3,NULL,NULL,NULL,NULL),
(5,3,NULL,NULL,NULL,NULL),
(6,3,NULL,NULL,NULL,NULL),
(7,3,NULL,NULL,NULL,NULL),
(11,3,NULL,NULL,NULL,NULL),
(12,3,NULL,NULL,NULL,NULL),
(13,3,NULL,NULL,NULL,NULL);